"""Run the pipeline on Kaggle's free GPU instead of Modal.

Modal is blocked on a workspace spend limit; Kaggle gives ~30 GPU-hours/week free.
A pushed kernel runs server-side on Kaggle's machines, so the laptop can close.

The pipeline (~70KB gzipped) is embedded directly in the kernel script, which avoids
the multi-step dataset upload API AND avoids needing the branch pushed to GitHub.

Auth: ~/.kaggle/access_token (KGAT bearer). The kaggle CLI only speaks the older
basic auth from kaggle.json, which is stale here, so this talks to REST directly.

    python kaggle_train.py                    # push + run the default config
    python kaggle_train.py --status           # check the last pushed kernel
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import pathlib
import tarfile
import urllib.error
import urllib.request

KAGGLE_USER = "samirsamal"
# Kaggle derives the slug from the title, not from what you push — this is the ref it
# actually assigned, and status/output lookups must use it.
SLUG = "indic-hindi-stt-whisper-lora"
CONFIG = "configs/hi_stt_fleurs_hindi_v2_kaggle.yaml"
API = "https://www.kaggle.com/api/v1"
# Kaggle preinstalls torch/transformers/datasets; these are the gaps.
EXTRA_DEPS = "peft>=0.11 torchcodec soundfile librosa pydantic>=2.6"


def _auth_header() -> str:
    tok = pathlib.Path.home() / ".kaggle" / "access_token"
    if not tok.exists():
        raise SystemExit("no ~/.kaggle/access_token — generate a KGAT token on Kaggle")
    return f"Bearer {tok.read_text().strip()}"


def _post(path: str, body: dict) -> dict:
    req = urllib.request.Request(
        f"{API}/{path}",
        data=json.dumps(body).encode(),
        headers={"Authorization": _auth_header(), "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        raise SystemExit(f"HTTP {e.code}: {e.read()[:400].decode('utf-8', 'replace')}")


def _get(path: str) -> dict:
    req = urllib.request.Request(f"{API}/{path}", headers={"Authorization": _auth_header()})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read())


def _payload() -> str:
    """gzip+b64 the source the kernel needs. __pycache__ excluded so the blob is
    reproducible and small."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for d in ("pipeline", "configs"):
            tar.add(d, filter=lambda t: None if "__pycache__" in t.name else t)
    return base64.b64encode(buf.getvalue()).decode()


def _kernel_source(config: str) -> str:
    return f'''# Auto-generated by kaggle_train.py — do not edit here, edit the repo.
import base64, io, os, subprocess, sys, tarfile

WORK = "/kaggle/working"
os.chdir(WORK)
tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz").extractall(WORK)

subprocess.run([sys.executable, "-m", "pip", "install", "-q", *{EXTRA_DEPS!r}.split()],
               check=True)

import torch
print(f"GPU: {{torch.cuda.get_device_name()}} | "
      f"{{torch.cuda.get_device_properties(0).total_memory/1e9:.0f}} GB | "
      f"torch {{torch.__version__}}", flush=True)

cmd = [sys.executable, "-m", "pipeline.run", "all", "--config", {config!r}, "--force"]
print("$ " + " ".join(cmd), flush=True)
rc = subprocess.run(cmd, check=False).returncode

# Surface metrics in the log so the result is visible without downloading output.
for p in sorted(__import__("pathlib").Path(WORK, "runs").glob("*/metrics.json")):
    print(f"\\n--- {{p.parent.name}}/metrics.json ---\\n{{p.read_text()}}", flush=True)
print(f"exit_code={{rc}}", flush=True)
sys.exit(rc)
'''


def push(config: str) -> None:
    src = f'PAYLOAD = "{_payload()}"\n' + _kernel_source(config)
    print(f"kernel script: {len(src)/1024:.0f} KB")
    resp = _post("kernels/push", {
        "slug": f"{KAGGLE_USER}/{SLUG}",
        "newTitle": "Indic Hindi STT — Whisper LoRA",
        "text": src,
        "language": "python",
        "kernelType": "script",
        "isPrivate": True,
        "enableGpu": True,       # free T4/P100, ~30 h/week quota
        "enableInternet": True,  # HF model + FLEURS download
        "datasetDataSources": [],
        "competitionDataSources": [],
        "kernelDataSources": [],
        "categoryIds": [],
    })
    print(json.dumps(resp, indent=2)[:600])


def status() -> None:
    out = _get(f"kernels/status?userName={KAGGLE_USER}&kernelSlug={SLUG}")
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=CONFIG)
    ap.add_argument("--status", action="store_true")
    a = ap.parse_args()
    status() if a.status else push(a.config)
