"""Run the pipeline on Kaggle's free GPU instead of Modal.

Modal is blocked on a workspace spend limit; Kaggle gives ~30 GPU-hours/week free.
A pushed kernel runs server-side on Kaggle's machines, so the laptop can close.

The pipeline (~70KB gzipped) is embedded directly in the kernel script, which avoids
the multi-step dataset upload API AND avoids needing the branch pushed to GitHub.

Auth: ~/.kaggle/access_token (KGAT bearer). The kaggle CLI only speaks the older
basic auth from kaggle.json, which is stale here, so this talks to REST directly.

    python kaggle_train.py                    # push + run the default config
    python kaggle_train.py --status           # check the last pushed kernel
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import pathlib
import tarfile
import urllib.error
import urllib.request

KAGGLE_USER = "samirsamal"
# Kaggle derives the slug from the title, not from what you push — this is the ref it
# actually assigned, and status/output lookups must use it.
SLUG = "indic-hindi-stt-whisper-lora"
CONFIG = "configs/hi_stt_fleurs_hindi_v2_kaggle.yaml"
API = "https://www.kaggle.com/api/v1"
# Verify with --shape after a push: kernels/pull echoes machineShape back, so a value
# the server rejected shows up as null rather than failing loudly at push time.
MACHINE_SHAPE = "nvidiaTeslaT4"
# Kaggle preinstalls torch/transformers/datasets; these are the gaps.
EXTRA_DEPS = "peft>=0.11 torchcodec soundfile librosa pydantic>=2.6"


def _auth_header() -> str:
    tok = pathlib.Path.home() / ".kaggle" / "access_token"
    if not tok.exists():
        raise SystemExit("no ~/.kaggle/access_token — generate a KGAT token on Kaggle")
    return f"Bearer {tok.read_text().strip()}"


def _post(path: str, body: dict) -> dict:
    req = urllib.request.Request(
        f"{API}/{path}",
        data=json.dumps(body).encode(),
        headers={"Authorization": _auth_header(), "Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        raise SystemExit(f"HTTP {e.code}: {e.read()[:400].decode('utf-8', 'replace')}")


def _get(path: str) -> dict:
    req = urllib.request.Request(f"{API}/{path}", headers={"Authorization": _auth_header()})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read())


def _hf_token() -> str:
    """Read the HF token from the standard cache path, NOT from the repo.

    Gated corpora (ai4bharat/*) need it at ingest. It gets injected into the generated
    kernel source at push time, so it lives in the private kernel and never in git —
    this repo is public. Absent token is fine for ungated runs (FLEURS, the model).
    """
    p = pathlib.Path.home() / ".cache" / "huggingface" / "token"
    return p.read_text().strip() if p.exists() else ""


def _payload() -> str:
    """gzip+b64 the source the kernel needs. __pycache__ excluded so the blob is
    reproducible and small."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for d in ("pipeline", "configs"):
            tar.add(d, filter=lambda t: None if "__pycache__" in t.name else t)
    return base64.b64encode(buf.getvalue()).decode()


def _kernel_source(config: str) -> str:
    return f'''# Auto-generated by kaggle_train.py — do not edit here, edit the repo.
import base64, io, os, subprocess, sys, tarfile

WORK = "/kaggle/working"
os.chdir(WORK)
# Injected at push time from ~/.cache/huggingface/token; empty for ungated runs.
if HF_TOKEN:
    os.environ["HF_TOKEN"] = os.environ["HUGGING_FACE_HUB_TOKEN"] = HF_TOKEN
    print("[hf] token present — gated datasets available", flush=True)
tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz").extractall(WORK)

subprocess.run([sys.executable, "-m", "pip", "install", "-q", *{EXTRA_DEPS!r}.split()],
               check=True)
# Kaggle ships torchao 0.10.0; peft's LoRA dispatcher RAISES on an old torchao rather
# than ignoring it, killing the run at adapter injection. We never quantize, and
# is_torchao_available() returns False cleanly when it is simply absent, so removing it
# beats upgrading into a conflict with Kaggle's pinned torch.
subprocess.run([sys.executable, "-m", "pip", "uninstall", "-y", "-q", "torchao"],
               check=False)

import torch
cap = torch.cuda.get_device_capability()
print(f"GPU: {{torch.cuda.get_device_name()}} | sm_{{cap[0]}}{{cap[1]}} | "
      f"{{torch.cuda.get_device_properties(0).total_memory/1e9:.0f}} GB | "
      f"torch {{torch.__version__}}", flush=True)


def run(*stages):
    for s in stages:
        cmd = [sys.executable, "-m", "pipeline.run", s, "--config", {config!r}, "--force"]
        print("$ " + " ".join(cmd), flush=True)
        rc = subprocess.run(cmd, check=False).returncode
        if rc:
            return rc
    return 0


# Kaggle hands this account a P100 (Pascal, sm_60) that its OWN torch 2.10+cu128 image
# has no kernels for, and machineShape cannot pin a T4 -- the API normalises it to a
# generic "Gpu". So make the P100 work instead of gambling on the assignment.
#
# Split by what each stage actually needs: ingest decodes FLEURS through
# datasets+torchcodec, which only works on Kaggle's current image, while train/evaluate
# read audio via soundfile and never import datasets. So prep the data first, THEN swap
# in a torch old enough to still ship Pascal kernels.
if cap[0] < 7:
    rc = run("ingest", "clean", "align")
    if rc:
        sys.exit(rc)
    print(f"[torch] sm_{{cap[0]}}{{cap[1]}} unsupported by {{torch.__version__}}; "
           f"installing a Pascal-capable build", flush=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    # torchvision moves WITH torch or its C++ ops fail to register
                    # ("operator torchvision::nms does not exist"), and transformers
                    # imports torchvision transitively, so a stale one breaks the whole
                    # library. 2.5.1 / 0.20.1 / 2.5.1 is the matched triple.
                    "torch==2.5.1", "torchvision==0.20.1", "torchaudio==2.5.1",
                    "--index-url", "https://download.pytorch.org/whl/cu121"], check=True)
    # Downgrading torch alone leaves the CURRENT transformers/peft/accelerate behind,
    # and peft then fails to IMPORT (it reaches for torch APIs 2.5 lacks). The pipeline
    # reads that as "peft missing". Pin the stack that shipped alongside torch 2.5.1;
    # 4.46 is also the first transformers with Seq2SeqTrainer(processing_class=...),
    # which train.py passes.
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "transformers==4.46.3", "peft==0.13.2", "accelerate==1.1.1"],
                   check=True)
    # Plain concatenation, not an f-string: this whole module is itself generated by an
    # f-string, so braces here would be consumed by the OUTER template.
    subprocess.run([sys.executable, "-c",
                    "import torch,transformers,peft;"
                    "print('[stack] torch='+torch.__version__+' tf='+transformers.__version__"
                    "+' peft='+peft.__version__)"], check=True)
    rc = run("train", "evaluate")
else:
    rc = run("ingest", "clean", "align", "train", "evaluate")

# Surface metrics in the log so the result is visible without downloading output.
for p in sorted(__import__("pathlib").Path(WORK, "runs").glob("*/metrics.json")):
    print(f"\\n--- {{p.parent.name}}/metrics.json ---\\n{{p.read_text()}}", flush=True)
print(f"exit_code={{rc}}", flush=True)
sys.exit(rc)
'''


def push(config: str) -> None:
    src = (f'PAYLOAD = "{_payload()}"\nHF_TOKEN = "{_hf_token()}"\n'
           + _kernel_source(config))
    print(f"kernel script: {len(src)/1024:.0f} KB")
    resp = _post("kernels/push", {
        "slug": f"{KAGGLE_USER}/{SLUG}",
        "newTitle": "Indic Hindi STT — Whisper LoRA",
        "text": src,
        "language": "python",
        "kernelType": "script",
        "isPrivate": True,
        "enableGpu": True,       # free GPU, ~30 h/week quota
        # MUST pin T4 (sm_75). Left to Kaggle's choice it assigned a P100 (sm_60),
        # which its own torch 2.10+cu128 image cannot emit kernels for. The selector is
        # `machineShape` (confirmed via kernels/pull); an `accelerator` key is silently
        # IGNORED, which is how two runs landed on a P100 while claiming to ask for T4.
        "machineShape": MACHINE_SHAPE,
        "enableInternet": True,  # HF model + FLEURS download
        "datasetDataSources": [],
        "competitionDataSources": [],
        "kernelDataSources": [],
        "categoryIds": [],
    })
    print(json.dumps(resp, indent=2)[:600])


def shape() -> None:
    """Did the server actually accept our machineShape, or silently drop it?"""
    md = _get(f"kernels/pull?userName={KAGGLE_USER}&kernelSlug={SLUG}").get("metadata", {})
    print(f"machineShape={md.get('machineShape')!r} enableGpu={md.get('enableGpu')!r}")


def status() -> None:
    out = _get(f"kernels/status?userName={KAGGLE_USER}&kernelSlug={SLUG}")
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=CONFIG)
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--shape", action="store_true")
    a = ap.parse_args()
    if a.shape:
        shape()
    elif a.status:
        status()
    else:
        push(a.config)
